version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: bank_db
    environment:
      POSTGRES_DB: bank_cards
      POSTGRES_USER: franck
      POSTGRES_PASSWORD: Franck@1204
    ports:
      - "5435:5434"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: