version: '3.8'
services:
  db:
    image: postgres:15
    container_name: bankdb
    environment:
      POSTGRES_DB: bankdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d

  app:
    build: .
    container_name: bank-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: docker